name: Test PyPI install
on: push

jobs:
  test-installation:
    name: Test PyPI install (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      # install basic first, then install pre-releases afterwards so we don't
      # pick up pre-releases of dependencies (e.g. pandas)
      run: |
        pip install --upgrade pip
        pip install openscm-twolayermodel
        pip install openscm-twolayermodel --pre
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Test installation
      run: |
        python scripts/test_install.py
