name: Test conda install
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 3'

jobs:
  test-installation:
    name: Test conda install (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Install package
      shell: bash -l {0}
      run: conda install -c conda-forge openscm-twolayermodel
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Test installation
      shell: bash -l {0}
      run: |
        which python
        python scripts/test_install.py
